/** 画风预设库（单一真相源）：移植自 juben `lib/style_templates.py` + 中文
 *  名称/简介（`lib/i18n/zh/templates.py`）+ 封面图（`public/style-thumbnails/`，
 *  原 1024px 压至 320px JPEG）；另有本仓自研的强约束预设，共 87 条。
 *  category：真人影像（实拍质感）/ 动画（漫剧美术）/ 纪录片美术（史料再现）。
 *  prompt 已剥「画风：」前缀——注入时统一加「全局视觉风格：」等前缀。 */
export interface StylePreset {
  id: string;
  name: string;
  /** 一句话卖点（juben 模板 tagline） */
  tagline: string;
  category: "真人影像" | "动画" | "纪录片美术";
  prompt: string;
  /** 封面参考图（public/style-thumbnails/{id}.jpg，320px） */
  cover: string;
}

export const STYLE_PRESETS: StylePreset[] = [
  {
    id: "live_photoreal_guard",
    name: "真人实拍·强约束",
    tagline: "photorealistic 开关 · 显式排除动漫/3D",
    category: "真人影像",
    // 按 gpt-image 官方指南设计：开头模式开关词直接触发写实模式，
    // 具体材质语言（皮肤纹理/毛孔/织物），末尾显式排除句压插画/3D 先验
    // （对「俊美古装人物」这类高插画先验主体尤其有效）
    prompt: "实拍真人照片，photorealistic photograph：真实演员出演，真实皮肤纹理与毛孔、真实发丝与织物细节；古装纪录片影像，35mm/50mm 电影摄影感，实景光源与柔和反射光，克制写实调色。严禁动漫、插画、漫画、3D 渲染、CG、游戏画质；禁止塑料皮肤、过度磨皮、网红脸、偶像滤镜与影楼写真感",
    cover: "/style-thumbnails/live_cinematic_ancient.jpg",
  },
  {
    id: "live_cinematic_ancient",
    name: "精品古装",
    tagline: "专业打光 · 电视剧质感",
    category: "真人影像",
    prompt: "古装真人纪录片 cinematic still，真实布景与服化道，35mm/50mm 摄影镜头感，柔和反射光，真实布料和皮肤细节，克制调色",
    cover: "/style-thumbnails/live_cinematic_ancient.jpg",
  },
  {
    id: "live_zhang_yimou",
    name: "张艺谋风格",
    tagline: "极致用色 · 仪式感",
    category: "真人影像",
    prompt: "张艺谋式真人电影摄影，真实布景和演员调度，强构图与高辨识色彩，35mm/50mm 镜头，真实材质纹理，克制胶片调色",
    cover: "/style-thumbnails/live_zhang_yimou.jpg",
  },
  {
    id: "live_ancient_xianxia",
    name: "古装仙侠",
    tagline: "临江仙 · 美白滤镜",
    category: "真人影像",
    prompt: "古装仙侠真人剧照摄影，真实演员与服饰材质，柔和棚拍反射光，50mm 镜头，细腻但不过度磨皮的自然皮肤质感，克制高清调色",
    cover: "/style-thumbnails/live_ancient_xianxia.jpg",
  },
  {
    id: "live_premium_drama",
    name: "精品短剧",
    tagline: "真人电视剧 · 大师构图",
    category: "真人影像",
    prompt: "真人纪录片式 cinematic still，真实拍摄现场和布景，35mm/50mm 镜头语言，自然或柔和反射光，真实皮肤与布料纹理，轻微生活痕迹，克制电影调色",
    cover: "/style-thumbnails/live_premium_drama.jpg",
  },
  {
    id: "live_cinema",
    name: "院线电影",
    tagline: "达芬奇调色 · 电影色调",
    category: "真人影像",
    prompt: "真人院线电影摄影，真实布景与演员表演，35mm/50mm 镜头，受控自然光或柔和布光，真实材质细节，DaVinci 式克制调色",
    cover: "/style-thumbnails/live_cinema.jpg",
  },
  {
    id: "live_spartan",
    name: "斯巴达史诗",
    tagline: "角斗士 · 浓重明暗",
    category: "真人影像",
    prompt: "古代战争真人纪录片剧照，真实演员、盔甲和尘土材质，35mm 镜头，低角度自然侧光，粗粝皮肤和金属磨损，克制史诗感",
    cover: "/style-thumbnails/live_spartan.jpg",
  },
  {
    id: "live_bladerunner",
    name: "银翼杀手",
    tagline: "极简野蛮 · 赛博粒子",
    category: "真人影像",
    prompt: "真人赛博朋克电影摄影，真实布景和可触摸材质，广角镜头，单一主色调控制，环境雾气与城市反射，粗野主义巨构空间，克制高反差调色",
    cover: "/style-thumbnails/live_bladerunner.jpg",
  },
  {
    id: "live_got",
    name: "权力的游戏",
    tagline: "冷色史诗 · 权谋",
    category: "真人影像",
    prompt: "中世纪真人剧照摄影，真实城堡布景、皮革、羊毛和金属磨损，冷色低饱和调色，自然窗光和火光，粗粝真实质感",
    cover: "/style-thumbnails/live_got.jpg",
  },
  {
    id: "live_breaking_bad",
    name: "绝命毒师",
    tagline: "南美滤镜 · 犯罪美学",
    category: "真人影像",
    prompt: "现代犯罪题材真人剧照摄影，真实街区和室内布景，35mm 镜头，强烈自然光与阴影，干燥空气质感，真实皮肤和服装细节，克制滤镜",
    cover: "/style-thumbnails/live_breaking_bad.jpg",
  },
  {
    id: "live_crime_investigation",
    name: "真实罪案调查",
    tagline: "纪实影像 · 冷静调查",
    category: "真人影像",
    prompt: "中国刑侦案件纪实风格，90年代南方沿海小城与老式派出所质感，低饱和青灰与钨丝灯暖黄交织，胶片颗粒，潮湿夜景，案卷档案感，真实犯罪纪录片剧照质感，克制严肃，高对比光影，不血腥",
    cover: "/style-thumbnails/live_crime_investigation.jpg",
  },
  {
    id: "live_kdrama",
    name: "韩剧偶像",
    tagline: "柔光美颜 · 浪漫偶像",
    category: "真人影像",
    prompt: "韩剧真人摄影，真实演员和现代室内外场景，柔和反射光，50mm 镜头，干净高级但不过度磨皮的商业影像，真实布料和肤质",
    cover: "/style-thumbnails/live_kdrama.jpg",
  },
  {
    id: "live_kurosawa",
    name: "黑泽明",
    tagline: "黑白高对比 · 人性史诗",
    category: "真人影像",
    prompt: "黑泽明式黑白真人电影摄影，真实外景、风雨尘土和演员调度，高对比自然光，35mm 镜头，粗粝胶片颗粒，人性史诗感",
    cover: "/style-thumbnails/live_kurosawa.jpg",
  },
  {
    id: "live_nolan",
    name: "诺兰",
    tagline: "IMAX · 冷蓝灰",
    category: "真人影像",
    prompt: "诺兰式真人电影摄影，IMAX 大画幅感，真实场景和物理光线，冷蓝灰克制调色，锐利镜头细节，深沉严肃氛围",
    cover: "/style-thumbnails/live_nolan.jpg",
  },
  {
    id: "live_tarantino",
    name: "昆汀",
    tagline: "高对比 · 暴力美学",
    category: "真人影像",
    prompt: "昆汀式真人犯罪片摄影，真实场景和演员调度，高对比光线，复古胶片色彩，35mm 镜头，大胆但物理可信的构图",
    cover: "/style-thumbnails/live_tarantino.jpg",
  },
  {
    id: "live_lynch",
    name: "大卫林奇",
    tagline: "平淡日常 · 超现实",
    category: "真人影像",
    prompt: "大卫林奇风格，在看似平淡无奇的日常表象下，隐藏着极度诡异、荒诞、令人毛骨悚然的超现实梦魇",
    cover: "/style-thumbnails/live_lynch.jpg",
  },
  {
    id: "live_anderson",
    name: "韦斯安德森",
    tagline: "糖果色 · 马卡龙",
    category: "真人影像",
    prompt: "韦斯安德森式真人摄影，真实微缩感布景但保持物理材质，正面构图，柔和均匀光，糖果色马卡龙配色，克制胶片质感",
    cover: "/style-thumbnails/live_anderson.jpg",
  },
  {
    id: "live_wong",
    name: "王家卫",
    tagline: "胶片颗粒 · 东方都市",
    category: "真人影像",
    prompt: "王家卫式真人电影摄影，真实东方都市空间，长焦/手持镜头感，霓虹和室内暖光，颗粒感胶片，慵懒暧昧氛围",
    cover: "/style-thumbnails/live_wong.jpg",
  },
  {
    id: "live_shaw",
    name: "邵氏武侠",
    tagline: "港式武侠 · 电影感",
    category: "真人影像",
    prompt: "港式武侠真人棚拍摄影，真实演员和可触摸布景，35mm 镜头，受控棚内灯光，布料、木器、金属道具质感清晰，克制电影调色",
    cover: "/style-thumbnails/live_shaw.jpg",
  },
  {
    id: "live_cyberpunk",
    name: "真人赛博朋克",
    tagline: "电影质感 · 极致高清",
    category: "真人影像",
    prompt: "真人赛博朋克电影摄影，真实街景布景、霓虹反射和湿润地面，广角镜头，物理可信材质，克制高饱和调色",
    cover: "/style-thumbnails/live_cyberpunk.jpg",
  },
  {
    id: "live_candlelit_period",
    name: "烛光正剧",
    tagline: "烛光低照 · 布料质感",
    category: "真人影像",
    prompt: "古装真人正剧摄影，真实布景与服化道，烛光 / 油灯 / 火盆形成的低照度暖光，高光不过曝，暗部保留布料、皮肤和器物细节，35mm/50mm 镜头，克制庄重的历史剧质感",
    cover: "/style-thumbnails/live_candlelit_period.jpg",
  },
  {
    id: "live_museum_reconstruction",
    name: "博物馆复原",
    tagline: "博物馆复原 · 克制可信",
    category: "真人影像",
    prompt: "历史博物馆复原纪录片影像，考古复原服饰与器物，真实棚内置景，中性柔和布光，材质、纹样、结构清晰可辨，画面克制、可信、无商业滤镜感",
    cover: "/style-thumbnails/live_museum_reconstruction.jpg",
  },
  {
    id: "live_jiangnan_mist",
    name: "江南烟雨",
    tagline: "水乡薄雾 · 含蓄安静",
    category: "真人影像",
    prompt: "江南水乡古装真人摄影，湿润空气与薄雾，白墙黛瓦、青石、木船、竹影，灰绿低饱和调色，柔和天光，画面安静、含蓄、有水汽层次",
    cover: "/style-thumbnails/live_jiangnan_mist.jpg",
  },
  {
    id: "live_silk_road_dust",
    name: "丝路黄沙",
    tagline: "大漠逆光 · 金褐粗粝",
    category: "真人影像",
    prompt: "西域边塞真人史诗摄影，干燥空气、逆光沙尘、粗粝皮革和布料，风蚀石壁与黄土色地貌，低饱和金褐调，真实盔甲与马具磨损，35mm 镜头的纪录片史诗感",
    cover: "/style-thumbnails/live_silk_road_dust.jpg",
  },
  {
    id: "live_bronze_ritual_epic",
    name: "青铜礼制",
    tagline: "青铜礼制 · 庄重对称",
    category: "真人影像",
    prompt: "商周青铜礼制真人史诗摄影，玄色、朱砂、青铜绿锈与火光，庄重对称构图，厚重礼器、玉器、丝帛和木构空间，低饱和高质感，肃穆王权仪式感",
    cover: "/style-thumbnails/live_bronze_ritual_epic.jpg",
  },
  {
    id: "live_noir_period_mystery",
    name: "古装黑色悬疑",
    tagline: "古装黑色 · 强阴影悬疑",
    category: "真人影像",
    prompt: "古装新黑色悬疑真人摄影，窄光束、强阴影、冷暖对撞，潮湿石板、旧木梁、纸窗与烟尘，压迫构图，真实服饰材质，严肃克制、不血腥",
    cover: "/style-thumbnails/live_noir_period_mystery.jpg",
  },
  {
    id: "live_16mm_archive",
    name: "16mm 档案",
    tagline: "16mm 胶片 · 年代资料感",
    category: "真人影像",
    prompt: "16mm 档案胶片纪实影像，轻微褪色、胶片颗粒、自然光、有限动态范围，真实服装和环境细节，带年代资料片质感但保持画面可读性",
    cover: "/style-thumbnails/live_16mm_archive.jpg",
  },
  {
    id: "live_social_realism",
    name: "社会现实主义",
    tagline: "社会现实主义 · 保留生活痕迹",
    category: "真人影像",
    prompt: "社会现实主义真人摄影，真实街区、乡镇或厂区环境，自然光与现场光，低饱和色彩，保留生活痕迹、旧墙面、粗糙布料和真实皮肤质感，不商业磨皮",
    cover: "/style-thumbnails/live_social_realism.jpg",
  },
  {
    id: "live_archaeology_field_doc",
    name: "考古现场纪实",
    tagline: "考古现场 · 自然硬光",
    category: "真人影像",
    prompt: "考古现场纪录片真人摄影，真实遗址、探方、土层、编号木签和工作棚环境，自然硬光与尘土空气，考古人员服装朴素，材质和地层细节清楚，影像克制、实证、带现场记录感",
    cover: "/style-thumbnails/live_archaeology_field_doc.jpg",
  },
  {
    id: "live_steppe_nomad_epic",
    name: "草原游牧史诗",
    tagline: "草原史诗 · 开阔地平线",
    category: "真人影像",
    prompt: "草原游牧历史史诗真人摄影，广阔地平线、低角度风、皮革、羊毛、毡帐、马具与金属饰件质感清晰，冷暖自然光，低饱和青绿与土黄色，人物和场景都有粗粝真实的纪实史诗感",
    cover: "/style-thumbnails/live_steppe_nomad_epic.jpg",
  },
  {
    id: "live_maritime_silk_road",
    name: "海上丝路",
    tagline: "海上丝路 · 海雾盐渍",
    category: "真人影像",
    prompt: "海上丝路历史真人史诗摄影，木帆船、港口、湿润海雾、盐渍木材、绳索、陶瓷和丝绸货物，低饱和青灰与暖金色，真实自然光与海面反射，兼具航海纪录片和历史剧质感",
    cover: "/style-thumbnails/live_maritime_silk_road.jpg",
  },
  {
    id: "live_forensic_history_doc",
    name: "历史调查纪实",
    tagline: "历史调查 · 档案特写",
    category: "真人影像",
    prompt: "历史调查纪录片真人摄影，档案室、遗址、复原现场与采访式布光交织，冷静中性调色，浅景深档案特写、真实纸张、灰尘、手套和器物细节，严肃、可信、带调查推进感",
    cover: "/style-thumbnails/live_forensic_history_doc.jpg",
  },
  {
    id: "live_song_elegance",
    name: "宋韵雅集",
    tagline: "宋韵雅集 · 留白克制",
    category: "真人影像",
    prompt: "宋韵雅集式真人摄影，克制留白、浅米与青灰色调、木构院落、纸窗、博古架、素雅衣料和细密器物陈设，镜头安静、清洁，兼具文人审美与城市生活气质，适合宋代及宋韵化整剧",
    cover: "/style-thumbnails/live_song_elegance.jpg",
  },
  {
    id: "live_suzhou_garden",
    name: "苏州园林",
    tagline: "园林借景 · 粉墙黛瓦",
    category: "真人影像",
    prompt: "苏州园林式真人摄影，借景、漏窗、太湖石、回廊、水面反光与粉墙黛瓦，柔和天光、留白构图和克制动线，人物与空间相互映衬，适合江南、士大夫、宅院和园林叙事的整剧美术",
    cover: "/style-thumbnails/live_suzhou_garden.jpg",
  },
  {
    id: "anim_3d_cg",
    name: "3D 游戏 CG",
    tagline: "影视级 · 虚幻引擎",
    category: "动画",
    prompt: "3D、游戏CG，影视级、虚幻引擎渲染",
    cover: "/style-thumbnails/anim_3d_cg.jpg",
  },
  {
    id: "anim_cn_3d",
    name: "国风 3D",
    tagline: "影视级 · 虚幻引擎",
    category: "动画",
    prompt: "国风3D、影视级、虚幻引擎渲染",
    cover: "/style-thumbnails/anim_cn_3d.jpg",
  },
  {
    id: "anim_kyoto",
    name: "商业动画 京都",
    tagline: "柔和赛璐珞 · 石立太一",
    category: "动画",
    prompt: "商业动画画风，柔和光影效果，轻柔的赛璐珞上色，柔和的漫射光线，清晰干净的细轮廓线条，参考京都动画作品，参考石立太一动画作品，2d动画",
    cover: "/style-thumbnails/anim_kyoto.jpg",
  },
  {
    id: "anim_arcane",
    name: "油画三渲二",
    tagline: "双城之战 · Arcane",
    category: "动画",
    prompt: "油画三渲二画风：参考《双城之战》(Fortiche / Arcane Style)画风",
    cover: "/style-thumbnails/anim_arcane.jpg",
  },
  {
    id: "anim_us_3d",
    name: "美式 3D 动画",
    tagline: "影视级 · 皮克斯",
    category: "动画",
    prompt: "美式3D动画电影风格、影视级、虚幻引擎渲染",
    cover: "/style-thumbnails/anim_us_3d.jpg",
  },
  {
    id: "anim_ink_wushan",
    name: "硬核水墨",
    tagline: "雾山五行 · 枯笔",
    category: "动画",
    prompt: "硬核传统2D水墨，视觉特点：保留生猛的毛笔枯笔笔触，张力拉满。参考《雾山五行》风格",
    cover: "/style-thumbnails/anim_ink_wushan.jpg",
  },
  {
    id: "anim_ink_papercut",
    name: "水墨剪纸",
    tagline: "雾山五行 · 重彩",
    category: "动画",
    prompt: "硬核传统2D水墨/剪纸，视觉特点：保留生猛的毛笔枯笔笔触，色彩借鉴中国传统重彩，战斗动作如中国武术般行云流水，张力拉满。参考《雾山五行》风格",
    cover: "/style-thumbnails/anim_ink_papercut.jpg",
  },
  {
    id: "anim_felt",
    name: "羊毛毡",
    tagline: "定格 · 真实光影",
    category: "动画",
    prompt: "羊毛毡风格，定格动画，真实光影，极致细节，氛围感，故事感，大师级构图",
    cover: "/style-thumbnails/anim_felt.jpg",
  },
  {
    id: "anim_clay",
    name: "黏土定格",
    tagline: "定格 · 大师构图",
    category: "动画",
    prompt: "黏土动画风格，定格动画，真实光影，大师级构图",
    cover: "/style-thumbnails/anim_clay.jpg",
  },
  {
    id: "anim_jp_horror",
    name: "日式惊悚",
    tagline: "低饱和 · 动画美学",
    category: "动画",
    prompt: "低饱和度色调，日式惊悚动画美学",
    cover: "/style-thumbnails/anim_jp_horror.jpg",
  },
  {
    id: "anim_kr_webtoon",
    name: "韩漫风格",
    tagline: "半写实 · 浪漫光影",
    category: "动画",
    prompt: "韩国网络漫画风格，半写实动漫风格，简洁柔和的线条画工，流畅的渐变阴影处理，肌肤呈现光泽感，采用柔色调色彩方案，营造浪漫光影效果，采用特写构图手法，营造浓郁的情感氛围，角色细节刻画精细",
    cover: "/style-thumbnails/anim_kr_webtoon.jpg",
  },
  {
    id: "anim_zzz",
    name: "次世代三渲二",
    tagline: "绝区零 · 法线调整",
    category: "动画",
    prompt: "次世代高精三渲二 (Next-Gen Cel-Shading 3D) Zenless Zone Zero style，极致干净的赛璐璐线条，结合3D的平滑运镜。面部阴影经过极其严格的法线调整，保证任何角度都唯美",
    cover: "/style-thumbnails/anim_zzz.jpg",
  },
  {
    id: "anim_ghibli",
    name: "吉卜力",
    tagline: "宫崎骏 · 温暖质感",
    category: "动画",
    prompt: "参考吉卜力动画电影风格，宫崎骏动画风格",
    cover: "/style-thumbnails/anim_ghibli.jpg",
  },
  {
    id: "anim_demon_slayer",
    name: "鬼灭 Ufotable",
    tagline: "粗描边 · 战斗番",
    category: "动画",
    prompt: "参考《鬼灭之刃》画风、参考Ufotable飞碟社画风，粗描边",
    cover: "/style-thumbnails/anim_demon_slayer.jpg",
  },
  {
    id: "anim_cyberpunk",
    name: "动画赛博朋克",
    tagline: "电影质感 · 高清",
    category: "动画",
    prompt: "参考动画赛博朋克电影，电影质感，极致高清画质",
    cover: "/style-thumbnails/anim_cyberpunk.jpg",
  },
  {
    id: "anim_bloodborne",
    name: "血源克苏鲁",
    tagline: "哥特 · 阴冷雾气",
    category: "动画",
    prompt: "参考血源诅咒画风，克苏鲁风格、哥特、写实阴暗、阴冷雾气、低饱和冷色调、虚幻引擎渲染",
    cover: "/style-thumbnails/anim_bloodborne.jpg",
  },
  {
    id: "anim_itojunji",
    name: "伊藤润二",
    tagline: "惊悚诡异 · 线条锐利",
    category: "动画",
    prompt: "惊悚诡异风、线条锐利，参考伊藤润二动画，数字漫画笔触、轻微颗粒感、哑光质感，惊悚压抑、悬疑感",
    cover: "/style-thumbnails/anim_itojunji.jpg",
  },
  {
    id: "anim_90s_retro",
    name: "90 年代日漫",
    tagline: "渡边信一郎 · 神山健治",
    category: "动画",
    prompt: "参考渡边信一郎作品风格，参考神山健治作品，90年代日本复古动漫风格，上世纪九十年代日漫风格的动漫，层次感，线条清晰，迷人氛围",
    cover: "/style-thumbnails/anim_90s_retro.jpg",
  },
  {
    id: "anim_handdrawn_cel",
    name: "手绘赛璐璐",
    tagline: "老派赛璐璐 · 铅笔线稿",
    category: "动画",
    prompt: "老派手绘赛璐璐动画，干净铅笔线稿与平涂阴影，胶片扫描颗粒，色彩温和但轮廓明确，角色结构稳定，背景为手绘美术板质感",
    cover: "/style-thumbnails/anim_handdrawn_cel.jpg",
  },
  {
    id: "anim_crayon_shinchan",
    name: "我有一只霸王龙",
    tagline: "马卡龙色调 · 夸张透视",
    category: "动画",
    prompt: "《蜡笔小新》经典赛璐珞动画风格，粗黑轮廓线，明亮柔和的马卡龙色调，Q版比例，夸张透视。",
    cover: "/style-thumbnails/anim_crayon_shinchan.jpg",
  },
  {
    id: "anim_documentary_rotoscope",
    name: "纪录转描动画",
    tagline: "转描动画 · 纪实严肃",
    category: "动画",
    prompt: "纪录片转描动画 rotoscope，基于真人动作轮廓的半写实二维动画，低饱和纪实色彩，细线稿与轻微纸面颗粒，严肃、克制、适合历史事件再现",
    cover: "/style-thumbnails/anim_documentary_rotoscope.jpg",
  },
  {
    id: "anim_papercut_shadow",
    name: "剪纸皮影",
    tagline: "剪纸皮影 · 民俗套色",
    category: "动画",
    prompt: "中国剪纸与皮影动画，平面侧影造型，宣纸和棉纸纤维，红、黑、金、靛蓝套色，关节与服饰纹样清晰，传统民俗舞台感，画面不出现文字",
    cover: "/style-thumbnails/anim_papercut_shadow.jpg",
  },
  {
    id: "anim_oriental_watercolor",
    name: "东方水彩绘本",
    tagline: "东方水彩 · 诗意晕染",
    category: "动画",
    prompt: "东方水彩绘本动画，透明水彩晕染、细腻线稿、柔和背景、低对比色彩、可见纸张纹理，画面温和、诗意、适合民间故事和抒情段落",
    cover: "/style-thumbnails/anim_oriental_watercolor.jpg",
  },
  {
    id: "anim_painterly_history",
    name: "厚涂历史动画",
    tagline: "厚涂历史 · 油画笔触",
    category: "动画",
    prompt: "厚涂历史二维动画，油画笔触与清晰角色轮廓结合，人物服饰、建筑与自然环境保持写实比例，光影厚重、色彩克制，适合严肃历史叙事的整剧动画风格",
    cover: "/style-thumbnails/anim_painterly_history.jpg",
  },
  {
    id: "anim_film_grain_2d",
    name: "胶片感二维",
    tagline: "胶片颗粒 · 回忆质感",
    category: "动画",
    prompt: "电影胶片感二维动画，手绘线稿、平涂色块、轻微漏光、尘点和胶片颗粒，低饱和调色，镜头感克制，适合历史回忆、近现代纪录动画和成人向剧情动画",
    cover: "/style-thumbnails/anim_film_grain_2d.jpg",
  },
  {
    id: "anim_tapestry_storybook",
    name: "织毯史诗",
    tagline: "织毯史诗 · 纹理叙事",
    category: "动画",
    prompt: "织毯与壁毯质感的二维史诗动画，纺织纹理、有限色彩、平面叙事构图、装饰性边缘图案，人物和场景像连续叙事织物画，适合神话、王朝史和民间史诗",
    cover: "/style-thumbnails/anim_tapestry_storybook.jpg",
  },
  {
    id: "anim_minimal_documentary",
    name: "极简纪录片动画",
    tagline: "极简纪录片 · 清晰剪影",
    category: "动画",
    prompt: "极简纪录片二维动画，有限色板、清晰剪影、干净几何场景、少量纸张纹理和柔和阴影，镜头语言克制，信息表达清楚，适合历史解释、人物传记和严肃科普整剧",
    cover: "/style-thumbnails/anim_minimal_documentary.jpg",
  },
  {
    id: "anim_ink_scroll_pan",
    name: "水墨长卷",
    tagline: "水墨长卷 · 气韵流动",
    category: "动画",
    prompt: "水墨长卷式二维动画，镜头像展开手卷一样横向游移，墨色浓淡、留白、皴擦和气韵流动清晰，适合历史叙事、山河行旅和诗意旁白段落",
    cover: "/style-thumbnails/anim_ink_scroll_pan.jpg",
  },
  {
    id: "anim_new_year_print",
    name: "木版年画",
    tagline: "木版年画 · 民俗高纯色",
    category: "动画",
    prompt: "中国木版年画二维动画，朱红、藤黄、靛蓝等高纯度民俗配色，粗线条、套色边缘和纸张纹理明显，喜庆但不廉价，适合民间故事、节令和市井群像",
    cover: "/style-thumbnails/anim_new_year_print.jpg",
  },
  {
    id: "anim_aardman_clay",
    name: "黏土定格",
    tagline: "黏土定格 · 手工捏塑",
    category: "动画",
    prompt: "Aardman 式黏土定格动画，手工捏塑质感、柔和棚拍光、可见指纹和微小瑕疵、喜剧性但真实的微缩布景，角色表演鲜明，适合整部剧保持手工温度的系列风格",
    cover: "/style-thumbnails/anim_aardman_clay.jpg",
  },
  {
    id: "anim_lotte_silhouette",
    name: "剪影纸偶",
    tagline: "黑色剪影 · 纸偶寓言",
    category: "动画",
    prompt: "Lotte Reiniger 式黑色剪影与纸偶动画，镂空轮廓、强烈逆光、装饰性星月与窗格图案、平面叙事构图，适合寓言、传说、历史旁白段落",
    cover: "/style-thumbnails/anim_lotte_silhouette.jpg",
  },
  {
    id: "anim_bakshi_raw",
    name: "粗粝成人动画",
    tagline: "粗粝成人动画 · 街头噪点",
    category: "动画",
    prompt: "Ralph Bakshi 式粗粝成人二维动画，夸张但不失体积的角色、粗线条、有限动画、褪色底色、街头气息和时代噪点，适合社会叙事、边缘人物和黑色历史段落",
    cover: "/style-thumbnails/anim_bakshi_raw.jpg",
  },
  {
    id: "anim_quay_surreal",
    name: "怪诞木偶",
    tagline: "怪诞木偶 · 幽闭梦魇",
    category: "动画",
    prompt: "Quay Brothers 式怪诞木偶定格动画，暗色木质场景、磨损器物、病理般的细节、幽闭空间、潮湿颗粒感和梦魇氛围，适合隐喻、记忆、心理段落",
    cover: "/style-thumbnails/anim_quay_surreal.jpg",
  },
  {
    id: "anim_80s_ova",
    name: "80年代 OVA",
    tagline: "80年代 OVA · 热血胶片感",
    category: "动画",
    prompt: "80年代日本OVA手绘动画，锐利轮廓、饱和但克制的赛璐璐上色、夸张高光、密集背景美术、胶片颗粒，适合史诗、热血与时代感",
    cover: "/style-thumbnails/anim_80s_ova.jpg",
  },
  {
    id: "anim_shinkai_clear",
    name: "新海诚式清透",
    tagline: "新海诚式 · 清透空气感",
    category: "动画",
    prompt: "新海诚式清透手绘动画，空气感、天空层次、玻璃和水面的高光、干净线条、明亮色彩，适合青春、记忆与城市空间段落",
    cover: "/style-thumbnails/anim_shinkai_clear.jpg",
  },
  {
    id: "anim_watanabe_jazz",
    name: "爵士动画",
    tagline: "爵士都市 · 松弛夜色",
    category: "动画",
    prompt: "渡边信一郎式爵士感动画，复古音乐氛围、城市夜色、自由镜头感、低饱和与暖色灯光并置、角色神态松弛，适合公路、都市和时代切片",
    cover: "/style-thumbnails/anim_watanabe_jazz.jpg",
  },
  {
    id: "anim_southpark_cutout",
    name: "剪纸电视动画",
    tagline: "剪纸拼贴 · 黑色幽默",
    category: "动画",
    prompt: "剪纸电视动画风格，粗糙纸偶轮廓、平面拼贴、轻微抖动感、简单背景与夸张表情，适合黑色幽默、群像讽刺和旁白段落",
    cover: "/style-thumbnails/anim_southpark_cutout.jpg",
  },
  {
    id: "doc_gongbi",
    name: "工笔画",
    tagline: "工笔绢本 · 线描典雅",
    category: "纪录片美术",
    prompt: "中国传统工笔画风格，绢本设色，线描精致，色彩典雅，参考宋代院体画与明代仇英人物画，适合人物 / 宫廷 / 仕女题材的视觉再现",
    cover: "/style-thumbnails/doc_gongbi.jpg",
  },
  {
    id: "doc_shanshui_scroll",
    name: "卷轴山水",
    tagline: "卷轴山水 · 散点透视",
    category: "纪录片美术",
    prompt: "中国卷轴山水画风格，水墨设色，散点透视，远近层次分明，参考北宋范宽 / 元代黄公望，适合古代地理 / 战场 / 山川场景的史料感再现",
    cover: "/style-thumbnails/doc_shanshui_scroll.jpg",
  },
  {
    id: "doc_qinglu_shanshui",
    name: "青绿山水",
    tagline: "青绿金线 · 庄丽山川",
    category: "纪录片美术",
    prompt: "中国青绿山水美术，石青石绿矿物设色、金线勾边、层峦叠嶂、云气与水脉流动，兼具庄丽与装饰性，适合宏阔山川、朝堂远景和王朝叙事",
    cover: "/style-thumbnails/doc_qinglu_shanshui.jpg",
  },
  {
    id: "doc_dunhuang_fresco",
    name: "敦煌壁画",
    tagline: "敦煌壁画 · 矿物厚涂",
    category: "纪录片美术",
    prompt: "敦煌壁画风格，矿物颜料质感，土红 / 石青 / 石绿 / 朱砂的厚涂笔触，线条带飞天韵律感，适合唐代宗教 / 乐舞 / 西域题材",
    cover: "/style-thumbnails/doc_dunhuang_fresco.jpg",
  },
  {
    id: "doc_late_qing_realism",
    name: "晚清纪实摄影",
    tagline: "晚清老照片 · 淡褐颗粒",
    category: "纪录片美术",
    prompt: "晚清民初纪实摄影风格，黑白或淡褐调，胶片颗粒感，自然光，参考 19 世纪末到 20 世纪初中国老照片质感，适合戊戌变法 / 辛亥前后 / 晚清官员 / 民俗题材",
    cover: "/style-thumbnails/doc_late_qing_realism.jpg",
  },
  {
    id: "doc_xieyi_ink",
    name: "写意水墨",
    tagline: "写意水墨 · 大面积留白",
    category: "纪录片美术",
    prompt: "中国写意水墨纪录片美术，水墨晕染、大面积留白、枯笔皴擦、墨色浓淡层次，强调气韵和空间关系，适合山川、战场气氛、梦境或意象化段落",
    cover: "/style-thumbnails/doc_xieyi_ink.jpg",
  },
  {
    id: "doc_han_silk_painting",
    name: "汉代帛画",
    tagline: "汉代帛画 · 朱黑古拙",
    category: "纪录片美术",
    prompt: "汉代帛画风格，绢帛底色、朱黑赭黄设色，平面化人物与云气纹，古拙线条，礼仪、神话和墓葬图像气质，画面有年代感但结构清晰",
    cover: "/style-thumbnails/doc_han_silk_painting.jpg",
  },
  {
    id: "doc_tang_tomb_mural",
    name: "唐代壁画",
    tagline: "唐墓壁画 · 丰润饱满",
    category: "纪录片美术",
    prompt: "唐代墓室壁画风格，矿物颜料、土红石绿、厚重墙面颗粒，饱满线条与丰润人物造型，适合仪仗、乐舞、贵族生活和胡汉交流题材",
    cover: "/style-thumbnails/doc_tang_tomb_mural.jpg",
  },
  {
    id: "doc_han_relief_rubbing",
    name: "汉画像石拓印",
    tagline: "汉画像石 · 刀刻拓印",
    category: "纪录片美术",
    prompt: "汉画像石与拓印美术，刀刻般线条、灰白石质肌理、仪式、车马、宴饮和神兽图像感，构图雄浑朴拙，适合汉代、墓葬和礼制题材",
    cover: "/style-thumbnails/doc_han_relief_rubbing.jpg",
  },
  {
    id: "doc_lacquer_red_black",
    name: "漆器美术",
    tagline: "漆器黑朱 · 深沉光泽",
    category: "纪录片美术",
    prompt: "中国古代漆器美术，黑漆底、朱红、金箔与贝母光泽，器物与服饰轮廓简洁，光泽克制而深沉，适合先秦、汉唐礼器与宫廷叙事",
    cover: "/style-thumbnails/doc_lacquer_red_black.jpg",
  },
  {
    id: "doc_blue_white_porcelain",
    name: "青花瓷",
    tagline: "青花瓷 · 釉面雅致",
    category: "纪录片美术",
    prompt: "青花瓷美术，白釉青花配色、釉面冷光、缠枝纹与器形轮廓清晰，雅致克制、留白充足，适合明清、器物、美学陈设与雅集题材",
    cover: "/style-thumbnails/doc_blue_white_porcelain.jpg",
  },
  {
    id: "doc_song_painting",
    name: "宋代院体",
    tagline: "宋代院体 · 细腻严谨",
    category: "纪录片美术",
    prompt: "宋代院体美术，克制细腻、留白分明、器物与建筑比例严谨，浅淡设色和温润纸绢肌理并存，适合宋代生活、宫廷礼仪与文人审美整剧",
    cover: "/style-thumbnails/doc_song_painting.jpg",
  },
  {
    id: "doc_byzantine_mosaic",
    name: "拜占庭马赛克",
    tagline: "拜占庭镶嵌 · 金色庄严",
    category: "纪录片美术",
    prompt: "拜占庭马赛克纪录片美术，金色背景、彩色玻璃和石粒镶嵌质感，正面化人物、庄严对称构图、宝石色彩和微微破损的墙面，适合中世纪、宗教、帝国叙事的整剧视觉",
    cover: "/style-thumbnails/doc_byzantine_mosaic.jpg",
  },
  {
    id: "doc_illuminated_manuscript",
    name: "泥金手抄本",
    tagline: "泥金手抄本 · 中世纪纹样",
    category: "纪录片美术",
    prompt: "中世纪泥金手抄本美术，羊皮纸底色、矿物颜料、金箔高光、平面化人物与建筑、装饰性植物纹样和边栏图案，适合欧洲中世纪、骑士、宗教和王朝题材",
    cover: "/style-thumbnails/doc_illuminated_manuscript.jpg",
  },
  {
    id: "doc_thangka_mineral",
    name: "唐卡重彩",
    tagline: "唐卡重彩 · 金线细密",
    category: "纪录片美术",
    prompt: "喜马拉雅唐卡矿物重彩美术，矿物颜料、金线、对称构图、细密纹样、宝石色彩和布面肌理，人物、山川和神圣空间高度装饰化，适合宗教、神话和高原历史题材",
    cover: "/style-thumbnails/doc_thangka_mineral.jpg",
  },
  {
    id: "doc_ukiyo_e_series",
    name: "浮世绘",
    tagline: "浮世绘木版 · 套色错位",
    category: "纪录片美术",
    prompt: "江户浮世绘木版画剧集风格，平面透视、清晰墨线、普鲁士蓝、朱红、赭黄和米色纸张，轻微套色错位与木版压印质感，适合东亚市井、旅途、武士与民俗题材",
    cover: "/style-thumbnails/doc_ukiyo_e_series.jpg",
  },
];

export const STYLE_CATEGORIES = ["真人影像", "动画", "纪录片美术"] as const;
